### ISSUE TITLE
IOBT still uses inverse kinematics?

### ISSUE THREAD

**Issue by UniWorkerPtyLtd** [oculus-samples/Unity-Movement#61] opened 2024-03-01 22:45 UTC
In non-IOBT mode ('low body tracking fidelty', 'inverse kinematics') if I hold my arm at 90 degrees and wave, my elbow also moves significantly. This is expected, since IK that is based purely on hands cannot know if I am moving just the wrist or my entire arm.

However, in IOBT mode ('high body tracking fidelty') I see a similar (albeit reduced) effect. This happens even if my elbow is in clear view of the cameras.

https://github.com/oculus-samples/Unity-Movement/assets/117140584/872c4238-3031-416f-8711-588be8019229

It's like IOBT is not actually tracking my elbow, and still doing IK based on my hand/wrist. Is this expected behaviour?

**Comment by sohailshafiiWk** [comment] 2024-03-13 14:28
Hello. There are some IK-based constraints in place that prevent weird poses when we have poor tracking. It looks like they are overly impacting the tracking in the case you described.  We are looking into this issue to see if we can relax the constraints without impacting other cases. We will let you know if we post a fix.

**Comment by UniWorkerPtyLtd** [comment] 2024-04-10 11:35
Hi @sohailshafiiWk thanks for looking into this. Is there any update?

**Comment by sohailshafiiWk** [comment] 2024-04-11 00:25
Thanks for your patience. The correction for this issue is in the works. We will repost here once the fix has been confirmed and roll-out has started.

**Comment by UniWorkerPtyLtd** [comment] 2024-05-04 23:34
Hi @sohailshafiiWk. How is this progressing? Keen to try it out.

**Comment by sohailshafiiWk** [comment] 2024-05-07 22:45
Thanks for bringing this to our attention. We have resolved the issue that you described when working with hands and IOBT.  For working with controllers, we there are other cases where we want to bias towards the info that the controllers are giving us over the vision-based IOBT.  As such, you will still see the IK overriding some of the elbow positions from IOBT.  Hopefully, this resolves your issue. We expect the updated OS to roll out in June.

**Comment by UniWorkerPtyLtd** [comment] 2024-05-09 04:04
Thanks @sohailshafiiWk. A related question: if IOBT still partially uses IK, does it support recalibrating arm length?

For example, if I wear the headset as an adult, use IOBT, then give the headset to a teenager, does IOBT 'see' the arms are now shorter? Or will it assume I have my arms bent from then on?

**Comment by sohailshafiiWk** [comment] 2024-05-14 20:06
Hello, autocalibration does not occur when the headset is removed and put on again. OVRManager has HMDMounted and HMDUnmounted events that you can use along with ResetBodyTrackingCalibration as described in https://developer.oculus.com/documentation/unity/move-body-tracking/#calibration-api

**Comment by UniWorkerPtyLtd** [comment] 2024-06-11 06:48
"We expect the updated OS to roll out in June."

Hi @sohailshafiiWk do you have a version number for this feature?

**Comment by sohailshafiiWk** [comment] 2024-06-11 18:52
Hello, v66 OS is the version number for this feature.

**Comment by UniWorkerPtyLtd** [comment] 2024-06-21 06:05
Confirmed. Looks much better now. Thanks!

**Comment by sohailshafiiWk** [comment] 2024-06-24 15:52
Thank you for the confirmation. Closing.

**Closed by sohailshafiiWk** 2024-06-24 15:52 UTC
