### ISSUE TITLE
 Issue with Full Body Tracking on Custom Avatar in Unity 2022.3.16f1

### ISSUE THREAD

**Issue by LoganLane** [oculus-samples/Unity-Movement#51] opened 2024-01-07 06:37 UTC
Hello,

I'm currently working with Unity version 2022.3.16f1 and Movement version 4.0.1, and I've encountered an issue related to full body tracking on a custom avatar, initially designed in Blender. Following the guidelines provided in the documentation ([link](https://developer.oculus.com/documentation/unity/move-body-tracking/)), I've imported the avatar into Unity as an FBX file.

After setting the animation type to Humanoid and enabling Translation DoF for the avatar configuration, everything appeared normal under the "Muscles & Settings" options, with all avatar parts moving correctly.

The problem arises when implementing full body tracking. Using my Quest Pro, I observed that the arm movements of the avatar are not tracking accurately. This issue persists even after testing with Unity's standard [Robot Kyle](https://assetstore.unity.com/packages/3d/characters/robots/robot-kyle-urp-4696) avatar, suggesting that the problem may not be exclusive to my custom model.

I am including a video clip demonstrating the specific tracking issue, along with the avatar file I've been using. Any insights or suggestions to resolve this tracking issue would be greatly appreciated.

Thank you for your assistance.

[Avatar.zip](https://github.com/oculus-samples/Unity-Movement/files/13852496/Avatar.zip)

https://github.com/oculus-samples/Unity-Movement/assets/34287344/3b742d8d-bf4b-4890-96d1-072cc3315fed

**Comment by andkim-meta** [comment] 2024-01-10 01:14
Hello, we have reproduced this issue on Unity 2022.3.16f1 and can confirm that it is present in Unity 2022, but not in Unity 2021. It looks like there is a change in how animation jobs work when root motion is enabled on the animator. We are currently looking into the issue, but for now, please try disabling the "Apply Root Motion" option on the Animator component of your character.

**Comment by LoganLane** [comment] 2024-01-11 19:00
Disabling "Apply Root Motion" resolved the issue. Looking forward to the future fix. Thanks!

**Comment by sohailshafiiWk** [comment] 2024-02-25 15:52
The fix for this specific root motion issue has landed in the #dev branch, and it will be merged into #main in the near future. If you run into more problems please create a new issue.

**Closed by sohailshafiiWk** 2024-02-25 15:52 UTC
