### ISSUE TITLE
Failed to start face tracking/eye tracking

### ISSUE THREAD

**Issue by Remicool** [oculus-samples/Unity-Movement#12] opened 2023-03-27 15:25 UTC
Hello Dear oculus Developers,
I kept getting this warning issue and cannot use the OVR Eye gaze script using Quest link with cable. Could you plz help me?

![7d8a39d73d1f3cb8731ba93987a9fad](https://user-images.githubusercontent.com/52769864/227987235-4901b0e2-18fb-4b1c-b7a1-37c8d8862953.png)

**Comment by andkim-meta** [comment] 2023-03-30 17:37
Hello,

Can you let us know the OS version that's being used on the Quest Pro over Link? Also, could you check the version of the Oculus software you're using for Link?

If it's possible, could you also attach logs by running the OculusLogGatherer from the steps described here: https://developer.oculus.com/resources/log-troubleshooting/

**Comment by ghazi-ge1803610** [comment] 2023-04-13 04:23
Hello im having the same issue i have followed all instruction and documentations for the build settings, and i have enabled all tracking features in the VR, in the app under Beta, and in the OVRCameraRig, updated the android manifest, using latest stable LTS recommend version of unity which is 2021.3.22f1, i have also the Oculus integration for unity V50.0, developer mode is  enabled, and im trying to run the MovmentAura scene in enity editor but i keep getting the following 
![image](https://user-images.githubusercontent.com/77442437/231651507-b69d4349-509b-4899-8474-fbeb78583626.png)

All Versions used:
![image](https://user-images.githubusercontent.com/77442437/231652423-98c3dcc0-ceca-4207-8e01-6c1cafea7e3d.png)
![image](https://user-images.githubusercontent.com/77442437/231652480-22916d2e-f839-427b-8574-2cbbdf107f95.png)

**Comment by ghazi-ge1803610** [comment] 2023-04-13 04:29
following up also my Meta quest pro is checked as a targeted device in the android XR, 

I just mainly want to be able to get eye and facial tracking working within the unity editor 

thank you...

**Comment by jainpuneet798** [comment] 2023-04-13 11:21
Hi I am facing the same issue while using - 

Unity Version: 2022.2.1f1
Oculus Integration 50.0

I am using Open XR though (that should not be a problem). The eye tracking features are disabled when I select the OVR Camera rig.

I am getting the same warning that "Failed to start eye tracking"

**Comment by sohailshafiiWk** [comment] 2023-04-13 22:43
Hi,

Can you please check the following settings?:
- Go to your Oculus Desktop app, click on "Settings", navigate to the "General" tab, and set Oculus as the active OpenXR Runtime
- Go to your Oculus Desktop app, click on "Settings", navigate to the "Beta" tab, and set the appropriate Oculus settings related to Link (enable developer runtime features, natural face expressions, eye tracking)
- In Unity, set Oculus as the Plug-in Provider in XR Plug-in Management for the Standalone platform.
- In Unity, check the Setup tool via the Oculus->Tools->Project Setup Tool menu.

**Comment by ghazi-ge1803610** [comment] 2023-04-14 17:54
hey @sohailshafiiWk, i have checked n did all that from before, as i said, but it still not tracking anything

**Comment by sohailshafiiWk** [comment] 2023-06-06 22:21
Sorry for the late reply. We have prepared some documents that might be able to address the problems mentioned. Can you please look at [https://developer.oculus.com/documentation/unity/unity-link/](https://developer.oculus.com/documentation/unity/unity-link/) and [https://developer.oculus.com/documentation/unity/move-troubleshooting/?](https://developer.oculus.com/documentation/unity/move-troubleshooting/)

**Comment by gayoungson** [comment] 2023-07-12 14:18
Hello, i have the same problem since changing to a new laptop (HP OMEN). I also get the following logs and my editor always crashes afterwards. I have tried various different solutions (opening the project with different Unity Editors, older OVR Plugin version, without Open XR installed etc.) but none has helped so far. The documents from @sohailshafiiWk didnt help me either. Any further suggestions would be very helpful!

<img width="972" alt="Screenshot 2023-07-12 133815" src="https://github.com/oculus-samples/Unity-Movement/assets/74600480/9a6fe36c-6a16-4569-a956-8878f91d1847">

**Comment by TheWiselyBearded** [comment] 2023-08-12 00:43
Hello, I am running into similar issues. The desktop Oculus App version is  56.0.0.109.155, the headset is on version 56.0.0.143.656.499814798. I am using Unity version 2021.3.29f1 and Oculus Integrations v55. The screenshot shows similar errors to those above. 

Despite configuring project settings appropriately, I can't run the face or eye tracking samples. Is there a fix for this?

![image](https://github.com/oculus-samples/Unity-Movement/assets/15572394/d48f230f-e6f2-47cb-8d78-eb321ee9cbef)

**Comment by HaikunHuang** [comment] 2023-08-12 00:47
May try to delete the Library and/or obj folder. And reopen the project. Best,Haikun HuangOn Aug 11, 2023, at 20:44, Alireza ***@***.***> wrote:﻿
Hello, I am running into similar issues. The desktop Oculus App version is  56.0.0.109.155, the headset is on version 56.0.0.143.656.499814798. I am using Unity version 2021.3.29f1 and Oculus Integrations v55. The screenshot shows similar errors to those above.
Despite configuring project settings appropriately, I can't run the face or eye tracking samples. Is there a fix for this?

**Comment by sohailshafiiWk** [comment] 2023-08-16 23:35
If the assertion failure is the same as the one reported in https://github.com/oculus-samples/Unity-Movement/issues/31, then we are looking into it. Please stay tuned for updates regarding that issue. If it's not the same issue, please let us know.

**Comment by TheWiselyBearded** [comment] 2023-08-22 18:38
@sohailshafiiWk , that looks to be the same issue. Thank you for the follow up!

**Comment by sohailshafiiWk** [comment] 2023-08-22 21:05
> @sohailshafiiWk , that looks to be the same issue. Thank you for the follow up!

If the problem is still occurring, can you  try the OculusLogGather discussed in https://developer.oculus.com/documentation/unity/unity-link/ to collect errors?

**Comment by sohailshafiiWk** [comment] 2023-09-06 17:08
Closing for now. Since the last messages were a duplicate of https://github.com/oculus-samples/Unity-Movement/issues/31, please open a new issue if another issue arises.

**Closed by sohailshafiiWk** 2023-09-06 17:08 UTC
