### ISSUE TITLE
Sample scenes InvalidOperationException: Avatar is null.

### ISSUE THREAD

**Issue by Pvanderlaan89** [oculus-samples/Unity-Movement#50] opened 2024-01-04 14:54 UTC
When I enter play mode with for example the MovementHighFidelity sample scene, I see the below error:

![2024-01-03_18-02-08](https://github.com/oculus-samples/Unity-Movement/assets/47057446/a7a8e541-1908-4e37-aed7-8d941bd23543)

Tracking seems to be off for multiple bones. There is an offset between the OVRCameraRig hand position and the HighFidelityFirstPerson hand mesh position (about 30cm or so) and also other bones of the avatar body seem to track incorrectly resulting in a stretched body.

Another issue, when I smile with my mouth closed, the avatar smiles with it's mouth open. 

Unity 2022.3.11f1, Meta all-in-one 60.0.0 and Meta movement 4.0.1.

**Comment by sohailshafiiWk** [comment] 2024-01-06 00:23
We are sorry that you are encountering issues with body and face tracking. We have duplicated the "Avatar is null" issue and can confirm it is caused by a function call (GetBoneTransform) that causes a null reference exception in Unity 2022 if the Animator does not have an avatar assigned.  This behavior is different from Unity 2021, so we will post a fix to the GitHub samples early next week. We are currently looking into the issue with the mouth opening during smiling and we will update you when we know more.

**Comment by andkim-meta** [comment] 2024-01-17 17:20
The "Avatar is null" issue should now be resolved with the version 4.1.0 release of the github package. For the face tracking issue with the avatar smiling when you're smiling with your mouth closed, please check that you are on v60 OS version or newer on the Quest Pro and let us know if you can reproduce the issue. If you can, please open a new issue separately.

**Closed by andkim-meta** 2024-01-17 17:20 UTC
